### PR TITLE
Jira REVIT-207446: Time of Peak

### PR DESCRIPTION
**Pull request by anchapin**
This PR fixes the issue in this [Jira ticket](https://jira.autodesk.com/browse/REVIT-207446). Refer to the spreadsheet "Update Index for E+ Report.xlsx" in the [Teams](https://nrel.sharepoint.com/:f:/r/sites/AutodeskTCF/Shared%20Documents/General/FY22-FY24_BLDG.10232.20.01.00/FY23/REVIT-207446?csf=1&web=1&e=SxCNjD) folder for more information.

Specifically, the two main sheets to refer to are "Inputs for code" and "SQL Query". I was able to figure out the SQL query being used to generate the column name order and entered it in cell D1 of the "SQL Query" sheet. To get the resulting ColumnName list, I ran a sample Energyplus model on my machine. Then utilized the SQL file, I copied it into the Teams folder, and a database viewer program to get the list using the query.

The "Inputs for code" sheet converts the list into the correct format to copy into the corresponding ruby files in the repo.

Note that I don't have time to test this out in REVIT yet. Hopefully, it can be confirmed quickly that this change fixes the issue.

Additionally, there is at least one other Jira issue that may also be served by the fix or something similar.

### CODE REVIEW

**Comment by eringold** [comment]
Verified this fixes the Jira ticket. With these changes, 'Time of Peak' on Design Psychrometrics page is correct: 
image
image

**Comment by eringold** [comment]
Also fixes https://jira.autodesk.com/browse/REVIT-207412

**Comment by MatthewSteen** [comment]
@eringold no need to (re)review, just organizing. Could you post some images of the the `207412` fix?

**Comment by eringold** [comment]
@MatthewSteen From REVIT-207412: 
v2023 (original, correct): 
image
v2024 (broken): 
image

this PR: 
image

**Pull request merged**
